### PR TITLE
Prevent cache metadata leak exception for image URL generation

### PR DESCRIPTION
**Pull request by kevin-dutra**
Some work to this effect was done in #768, but that appears to have been abandoned. The issue still remains though. As part of the URL generation for the image URLs, cache metadata will be leaked, causing an exception to be thrown from the `EarlyRenderingControllerWrapperSubscriber`.

Similar logic can be found in `MailManager::mail()`, although in that case, the metadata is simply ignored because the emails are not cached. In this case, we actually *do* want that metadata to be incorporated.

### CODE REVIEW

**Review by stevenspasbo — APPROVED** [review]
Looks good to me

**Comment by klausi** [comment]
Looks good to me. Merged from 8.x-4.x and waiting on the tests to pass.

**Comment by benjy** [comment]
Looks good to me, all the tests passed but PHPCS failed, maybe a new rule since the code was added. Do we want to fix that here or in a follow-up?

**Comment by klausi** [comment]
Strange that the ImageStyle::load() call only fails now and not on 8.x-4.x.

I can make an exception for it in a follow-up commit.

**Comment by klausi** [comment]
Thanks everybody, also for your patience!

**Pull request merged**
