### PR TITLE
Add logging when developing.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Is this a useful answer to #566

### CODE REVIEW

**Comment by fubhy** [comment]
Yes, we should do this, but this is the wrong place.

If you want to give it another shot, this would be the right place: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php

**Comment by clemens-tolboom** [comment]
Below the feedback from @pmelab https://github.com/drupal-graphql/graphql/issues/566#issuecomment-385648742

---

Thanks @clemens-tolboom !
To merge this, we need to change the approach a little.

- [ ] Errors should be logged on a processor level, since not all requests come from the HTTP endpoint (e.g. graphql_twig).
- [ ] IMO errors should also be logged when not in debug mode. If they happen in production, I'm even more interested what happened 😃
- [ ] Right now when debug mode is off, it will only log "Internal Server Error", which is not helpful.

The GraphQL library already accepts custom error handlers, we just have to use them:
http://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting

As far as I can tell they have to be added to the ServerConfig object: https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php#L133

Do you have time to look into that? Else I will pick it up at some point in the future 😉

**Comment by fubhy** [comment]
Yeah. The first point that Philipp mentioned is also what I mentioned. "Should be done in the Processor" => https://github.com/drupal-graphql/graphql/blob/8.x-3.x/src/GraphQL/Execution/QueryProcessor.php

And yes, probably with a custom error handler.

I can't work on this in the near future. Feel free to pick it up whenever you have time!

**Comment by clemens-tolboom** [comment]
I cannot take this as I run into lot's of trouble using GraphQL which needs my attention too :-(

**Comment by fubhy** [comment]
Continued in #662

**Comment by clemens-tolboom** [comment]
👍

**Pull request closed without merging**
