### PR TITLE
#1151 - return an empty array instead of NULL when there are no referenced entities

### PR DESCRIPTION
**Pull request by rthideaway**
fixing https://github.com/drupal-graphql/graphql/pull/1165 correctly

### CODE REVIEW

**Comment by seanflahertyT4** [comment]
Hi, I'm sorry but what is the design intent of returning an empty array OR null?  why isn't the element just removed from the list?  

[This is unexpected, breaking behaviour and a security vulnerability.  ](https://github.com/drupal-graphql/graphql/issues/1027)

**Comment by seanflahertyT4** [comment]
since the default `REVISIONS` is `LATEST`, I suggest making the { status:"1" } filter a default condition as well.  

`  query {
    nodeQuery(filter: {conditions: [
      {field: "status", value: "1"}
      {field: "type", value: "content_type"}
    ]}, revisions: LATEST) {
      count
  }
}
`

**Comment by klausi** [comment]
Thanks, looks like test coverage is missing here as well, adding the "needs tests" tag.

**Comment by klausi** [comment]
Continued in #1265

**Pull request closed without merging**
