### PR TITLE
Drupal 9 compatibility for 3.x

### LINKED ISSUE #1011: Drupal 9 compatibility for 3.x
Given how much more work needs to be done for a stable release of 4.x, it would be worthwhile resolving Drupal 9 compatibility issues in 3.x and releasing 3.1.

### PR DESCRIPTION
**Pull request by Leksat**
Fixes #1011. Closes #1067. Closes #1012.

Based on #1067, with some small adjustments. See the description in #1067.

### CODE REVIEW

**Comment by Leksat** [comment]
For some reason Travis build does not start. I tried twice but no luck.

**Comment by pmelab** [comment]
The 8.8 test fails due to some composer conflicts. But do we still need to test 8.8?

**Review by pmelab — APPROVED** [review]

**Comment by carolpettirossi** [comment]
I created a patch from #1102, applied successfully to 3.x-dev, and worked perfectly in our case.

I wonder if we can get this released soon to keep 3.x at least minimally maintained.

**Comment by joaogarin** [comment]
I don't use myself 3.x so tagged here people who are using it (like @carolpettirossi ) I think if fine by them we could really make a release of it (long overude :P) any objections @klausi ?

**Comment by pmelab** [comment]
Released! https://www.drupal.org/project/graphql/releases/8.x-3.1

**Comment by joaogarin** [comment]
Yew that's awesome :tada:

**Pull request merged**
