### PR TITLE
Derive fields based on field definitions instead of storage definitions.

### PR DESCRIPTION
**Pull request by fubhy**
This PR should wait for https://github.com/drupal-graphql/graphql/pull/686

### CODE REVIEW

**Comment by wimleers** [comment]
That was fast! 🚀 Paves the path for #571 and #429!

**Comment by wimleers** [comment]
It seems like this is basically removing `config:field.storage.*` all over. I can see that if it's still relying on the `entity_field_info` cache tag. But that's also being removed.

I don't fully grok this. Could you explain this a bit? :) 🙏

**Comment by rafatwork** [comment]
Awesome work! My first (manual) tests are very positive.

This change does have an impact on existing queries however. For example, I have a node bundle "article" with a "field_whatever" field. Currently (in 3.x-beta8) this can be queried as such:
```
query {
  nodeById(id: "123456") {
    ... on Node {
      fieldWhatever
    }
  }
}
```

With this change, the query has to be changed to
```
query {
  nodeById(id: "123456") {
    ... on NodeArticle {
      fieldWhatever
    }
  }
}
```

Which isn't a big deal (for me at least), but might break existing implementations. Something that might be worth mentioning in the release notes.

**Comment by wimleers** [comment]
> Currently (in 3.x-beta8) this can be queried as such:

Oh wow, that sounds like a pretty big bug in the schema today? Because AFAICT that means that all bundle-specific fields are portrayed to be present on _all_ bundles of a specific entity type.

Thanks @rafatwork for testing this!

**Comment by wimleers** [comment]
Oh and when I wrote

> That was fast! 🚀 

12 days ago, I meant the fact that #686 landed. Sorry for not being more clear.

Note that @fubhy and I have had some follow-up discussion over there, see https://github.com/drupal-graphql/graphql/pull/686#issuecomment-428472604.

**Comment by fubhy** [comment]
> > Currently (in 3.x-beta8) this can be queried as such:
> 
> Oh wow, that sounds like a pretty big bug in the schema today? Because AFAICT that means that all bundle-specific fields are portrayed to be present on _all_ bundles of a specific entity type.
> 
> Thanks @rafatwork for testing this!

That is there due to legacy compatibility. We have to make a decision now whether we want to throw that compatibility out for the release or not. It is (was) not really a problem so not really a bug. Just a more condensed schema.

**Comment by duartegarin** [comment]
Hey @fubhy ,

I've added the fix for two tests failing on #692 (sorry about the delay).

The third test however (BundleLessEntityTest) is a bit trickier as I'm not that familiar with the codebase.

It seems to me that the issue is caused by the changes in EntityFieldTypeDeriver.php, particularly this code:

```
    $propertyDefinitions = $itemDefinition->getPropertyDefinitions();
    if (count($propertyDefinitions) <= 1) {
      return [];
    }
```

When it gets to the field_test added to the user entity, this check fails and so returns an empty array.

Before the change, when we were using a field definition instead of item definition the code worked:

```
    $propertyDefinitions = $fieldDefinition->getPropertyDefinitions();
    if (count($propertyDefinitions) <= 1) {
      return [];
    }
```

I'm not totally sure what the rationale is behind the count of property definitions so thought I'd flag it first.
Let me know if that rings any bells of if I can help further.

**Comment by duartegarin** [comment]
Also, probably worth noting 8.x-3.x breaks Graphql redirect (cc. @peterkeppert)

I don't think it's this update though.

```
Error: Uncaught ArgumentCountError: Too few arguments to function Drupal\graphql_core\Plugin\GraphQL\Fields\Routing\Route::__construct(), 6 passed in /app/drupal/web/modules/contrib/graphql_redirect/src/Plugin/GraphQL/Fields/Routing/RedirectAwareRoute.php on line 89 and exactly 8 expected in /app/drupal/web/modules/contrib/graphql/modules/graphql_core/src/Plugin/GraphQL/Fields/Routing/Route.php:98
```

**Comment by fubhy** [comment]
Thanks for the help @duartegarin! Much appreciated :-)

**Comment by duartegarin** [comment]
No worries @fubhy , thanks for getting this across the line!

**Pull request merged**
