### PR TITLE
Limit methods to POST and GET.

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by dawehner** [comment]
Note: This is what the routing system does by default anyway ...

**Comment by fubhy** [comment]
@dawehner Yeah, I know. This was not meant to be merged but just to show something to a colleague.

**Comment by dawehner** [comment]
He. Well I'm wondering whether its good practise to do so though

Sebastian Siemssen <notifications@github.com> schrieb am Mi., 8. Nov. 2017
um 13:32 Uhr:

**Comment by fubhy** [comment]
Well we are handling this in our Nginx config before it even hits Drupal.

**Comment by fubhy** [comment]
Preflight requests that is.

**Pull request closed without merging**
