### PR TITLE
refactor(dataproducer): ContextAwarePluginBase got removed, make it work for Drupal 10

### PR DESCRIPTION
**Pull request by klausi**

### CODE REVIEW

**Comment by akhomy** [comment]
Hey @klausi .

It seems this PR can break some data producers that are using some of the traits from the `ContextAwarePluginBase`.
The main case could be using the translation `$this->t(`.
Used traits:
```
  use ContextAwarePluginTrait;
  use TypedDataTrait;
  use StringTranslationTrait;
  use DependencySerializationTrait;
  ```
  What do you think? Should we move traits as well in order to support compatibility?

**Comment by klausi** [comment]
Hi, yes makes sense to add back the traits to the base class. That is a bit unfortunate, sorry!

**Comment by akhomy** [comment]
No worries, I'll see if I can prepare PR.

**Comment by akhomy** [comment]
Created PR with update - https://github.com/drupal-graphql/graphql/pull/1308

**Pull request merged**
