### PR TITLE
Drupal 9 compatibility

### PR DESCRIPTION
**Pull request by codingsasi**

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks, but this is an exact duplicate of PR https://github.com/drupal-graphql/graphql/pull/1012.

**Comment by joaogarin** [comment]
Sounds like #1012 comes later than this. Could we focus on one PR only?

**Comment by joaogarin** [comment]
Quick question, how is this different than https://github.com/drupal-graphql/graphql/pull/1028 ?

**Comment by hugovk** [comment]
> Sounds like #1012 comes later than this. Could we focus on one PR only?

PR #1012 came before this PR (#1028), you can tell from the numbers :)

> Quick question, how is this different than #1028 ?

This is #1028, I assume you mean #1012. They're not different. They're identical. I suggest this later #1028 is closed.

Also, #1067 builds on #1028, so I suggest #1028 is also closed in favour of #1067.

**Comment by Luigisa** [comment]
This request has already been resolved.
I am closing it.
Thank you

**Pull request closed without merging**
