### PR TITLE
tests(Travis CI): Switch testing to Drupal 8.9.x and 9.0.x

### PR DESCRIPTION
**Pull request by klausi**
Update the Drupal core versions we want to test against.

### CODE REVIEW

**Review by rthideaway — APPROVED** [review]
looks good to me!

**Comment by rthideaway** [comment]
@klausi can we also sync the code from github to drupal? latest three commits are not yet synced there -> https://git.drupalcode.org/project/graphql/-/tree/8.x-4.x
or do we have some helper script/job to do that?

**Comment by klausi** [comment]
We can, did it now! This is a manual step we always have to do, which is a bit annoying. We could setup an auto sync on some server, I did that in the past for other projects.

**Comment by rthideaway** [comment]
yep that would be great indeed!

**Pull request merged**
