### PR TITLE
Add the executable view as a cache dependency for not paged views.

### PR DESCRIPTION
**Pull request by chindris**
Otherwise, the cache is invalidated when new entities appear in the view.

This also fixes a bug: the returned results has to be an array.

### CODE REVIEW

**Comment by pmelab** [comment]
@chindris You could also override `resolve` itself and build your `CacheableValue`s yourself as you need them. The default implementation is just for convenience.

**Comment by pmelab** [comment]
Then you don't need to load the executable twice.

**Comment by fubhy** [comment]
So is that the path that we want to recommend @pmelab? What about the stuff we discussed during our chat about this issue?

**Comment by pmelab** [comment]
Yes, I came to that conclusion after thinking about what we discussed. I think for complex uses cases like views integration where we need fine grained control, it's better to remove an automatism that adding a new one.

**Comment by fubhy** [comment]
@chindris Can you update your PR according to @pmelab's suggestion?

**Comment by fubhy** [comment]
Closing because stale.

**Pull request closed without merging**
