### PR TITLE
Edit twig annotation regex to look for query ending

### PR DESCRIPTION
**Pull request by fjgarlin**

### CODE REVIEW

**Comment by pmelab** [comment]
Just curious: What happened without searching for the query end?

**Comment by fjgarlin** [comment]
If there are multiple twig comments it will wrap too much inside the query. See #366.

**Comment by pmelab** [comment]
Ah, I see. I'm not sure we should even allow this 😄 
But in any case, it would be better to make the group non-greedy instead of searching for an end:
```
/{#graphql\s+(?<query>.*?)\s+#\}/s
```

**Comment by fjgarlin** [comment]
Cool. Just changed to the one you suggested.

**Pull request merged**
