### PR TITLE
Move entity fields to graphql_core. (#64)

### PR DESCRIPTION
**Pull request by peterkeppert**

### CODE REVIEW

**Comment by pmelab** [comment]
There is actually more to clean up and move:

* `RouteEntity` is also generic and can move to `graphql_core`
* `EntityBasicFieldsTest` and `EntityQueryTest` should also move.
* #236 adds more entity generic properties. If one PR is merged, the other one has to adapt.

**Comment by peterkeppert** [comment]
Thanks for the review. I have made the following changes:
- Moved RouteEntity to graphql_core.
- Removed EntityQueryTest and related queries from graphql_content module.
- Added all_nodes entity query test to graphql_core EntityQueryTest (the rest of removed tests are in my opinion already covered there).
- Used original EntityBasicFieldsTest (before #236) for graphql_core and updated it to run without graphql_content dependency. I left graphql_content's EntityBasicFieldsTest intact.

**Comment by fubhy** [comment]
@peterkeppert Can you add the new fields from https://github.com/fubhy/graphql-drupal/pull/236? Once that's added, I am going to merge this PR.

**Comment by peterkeppert** [comment]
Right, PR updated.

**Comment by fubhy** [comment]
@peterkeppert Beautiful. Will merge it once the tests are green.

**Comment by fubhy** [comment]
Thanks!

**Pull request merged**
