### PR TITLE
Entity reference: Scope direct queries

### PR DESCRIPTION
**Pull request by defr**
Previously, all the queries where exposed straight on the entity type, not taking into account the bundles on which the field actually appears.

This changes it to keep exposing the base fields on the entity type interface, but expose the configurable fields only on the bundles they're attached to.

### CODE REVIEW

**Comment by defr** [comment]
The reverse hunk makes no sense, sorry about that. Fix coming up.

**Comment by defr** [comment]
For reverse queries, the situation is more complicated, because each field instance can define its own list of target bundles ; fetching the list of possible target bundles if the entity reference field isn't using the default selection plugin is also going to be problematic. I've reverted that change, and changed the scope of that PR to only be about forward references for now.

**Comment by defr** [comment]
Sorry for the misclick

**Comment by pmelab** [comment]
Looks good, thank you very much!

**Pull request merged**
