### PR TITLE
chore(eslint): Upgrade package

### PR DESCRIPTION
**Pull request by joaogarin**
Screenshot from 2020-07-21 15-51-05

Retested it. Looks good. now it should work :pray:

### CODE REVIEW

**Comment by klausi** [comment]
Hm, but the error on https://github.com/drupal-graphql/graphql/network/alerts is in Voyager ... you are changing the Explorer file here?

**Comment by joaogarin** [comment]
Updated now also Voyager they both needed eslint and babel eslint updates. Retested both this should now address all of it

**Comment by klausi** [comment]
@joaogarin can you update this branch and check if there are other updates? I think dependabot already opened some more.

**Comment by joaogarin** [comment]
yes will revisit this today :+1:

**Comment by joaogarin** [comment]
Tested it again. Looks ok. Some changes where affected by prettier but still I would say that is ok? its mostly some code style / formatting

**Review by klausi — APPROVED** [review]
yep, looks good!

**Pull request merged**
