### PR TITLE
Fix broken authentication

### PR DESCRIPTION
**Pull request by acha5066**
It appears a recent change broke simple_oauth integrations using the Authorization Bearer header. After debugging I was able to track it to this line and after clearing the cache it works again.

Any feedback?

### CODE REVIEW

**Comment by ayalon** [comment]
This is critical. Please create a new release. Else everyone using oauth2 will run into troubles.

**Comment by pmelab** [comment]
Introduced by #766. So for `basic_auth` to work, we have to add it as an `_auth` option, but this simultaneously removes all other auth providers.

Solutions that come into my mind:
1. Add _all_ existing auth providers to the route.
2. Make auth providers a configurable.
3. Combined: If no providers are configured with 2., 1. kicks in and adds them all.

**Comment by acha5066** [comment]
Updated so that any authentication providers that are enabled will be added to the _auth property. Tested with basic_auth and oauth2.

**Comment by fubhy** [comment]
Cool, thanks!

**Pull request merged**
