### PR TITLE
Fix #243

### LINKED ISSUE #243: Notices in createGenericInputFilterDefinition()
```
Notice: Undefined variable: displayId in Drupal\graphql_views\Plugin\Deriver\ViewFilterInputDeriver->createGenericInputFilterDefinition() (line 136 of /Users/moshe.weitzman/reps/graphql/modules/graphql_views/src/Plugin/Deriver/ViewFilterInputDeriver.php).
```

Not sure what the right variable should be.

### PR DESCRIPTION
**Pull request by ClemensSahs**
Fix #243

### CODE REVIEW

**Comment by fubhy** [comment]
@ClemensSahs Cool, thanks! Have you considered joining us in the Drupal Slack community? We have a #graphql channel there :)

**Comment by ClemensSahs** [comment]
@fubhy currently not but sure I will. ;) I go to the local meetups in Hamburg

**Comment by fubhy** [comment]
The local meetups for #graphql or #drupal? :)

**Comment by ClemensSahs** [comment]
drupal

**Pull request merged**
