### PR TITLE
fix(DataProducer): Fix missing cacheability bubble up on entity translations data producer

### PR DESCRIPTION
**Pull request by mxr576**

### CODE REVIEW

**Comment by mxr576** [comment]
The failure in ` tests/src/Kernel/DataProducer/Routing/RouteEntityTest.php`  should be unrelated... right?

**Update**: Yes, I see the same on #1346

**Comment by klausi** [comment]
Thanks - looking into the PHStan fails in #1354

**Comment by klausi** [comment]
That is resolved, can you merge the 8.x-4.x branch and try again here?

**Comment by klausi** [comment]
Thanks a lot!

**Pull request merged**
